### ISSUE TITLE
Error running app

### ISSUE THREAD

**Issue by 53Cheese** [akazdayo/pixelart#11]
The website said there is an error running the app and contact support if it happens multiple times I tried multiple times and it kept saying there is an error running the app

**Comment by akazdayo** [comment]
Dear 53Cheese, 
Thank you for the report.

Unfortunately, this app's server is regularly down due to a memory leak bug(currently can use the app).
I'm currently working on fixing the server, and I apologize for not resolving this issue completely at the moment.
