### ISSUE TITLE
Error running app. If this keeps happening, please contact support.

### ISSUE THREAD

**Issue by Rabneba** [akazdayo/pixelart#14]
Hi! Plz, run the app.  Super need it right now... ) +rep

**Comment by akazdayo** [comment]
Hi, Rabneba.
Thank you so much for use the my app.
I'm sorry for the server down.
I will look at the logs and see if I can find the cause.

**Comment by akazdayo** [comment]
if it happens again, you can do install the this app for your PC.
It requires a little Python and shell command knowledge, can be done in the following way.
# Using rye (Recommended)
rye can be downloaded [here](https://rye.astral.sh/).
```bash
git clone https://github.com/akazdayo/pixelart.git
cd pixelart
rye sync
rye run streamlit run main.py
```
# Using venv
Recommended python version is 3.10.14
```bash
git clone https://github.com/akazdayo/pixelart.git
cd pixelart
python -m venv .venv
# entry the venv (if you using linux and bash: $ source .venv/bin/activate)
pip install -r requirements.txt
streamlit run main.py
```
