### ISSUE TITLE
App is down.

### ISSUE THREAD

**Issue by SPDStrife** [akazdayo/pixelart#17]
I am getting this screen when attempting to access the app, which is strange since it was working just an hour ago. Other streamlit apps are working fine for me so I'm not sure what the issue is.
![Screenshot (50)](https://github.com/user-attachments/assets/c8786d30-b55b-4704-836e-472661f164d7)

**Comment by akazdayo** [comment]
Hello SPDStrife.
Thank you for using my app.
this error is server-side error so, cannot use until I reboot.
sorry for the inconvenience.
