### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by asianjeff55** [akazdayo/pixelart#20]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://pixelart.streamlit.app/akazdayo/pixelart/main/main.py) has gone over its resource limits. Access to the app is temporarily limited. is there anyway I could get access to this application or download it on my PC?

**Comment by akazdayo** [comment]
Hello asianjeff55,
Sorry for inconvenience.

> is there anyway I could get access to this application or download it on my PC?

Yes, You can host(it's free) or download the this web-app.
Please refer to the following.

# Download
https://github.com/akazdayo/pixelart/issues/14#issuecomment-2348237027

# Host
1. Fork(on GitHub) the this repository
2. Sign up for [Streamlit official website](https://streamlit.io/) with GitHub
3. Click the "Create app" button in the upper right.
4. Click the "Deploy now" button.
5. Select the "asianjeff55/pixelart" on Repository section.
6. Select the "main.py" on Main file path section.
7. Click the "Deploy" button.
8. Congraturation!
